import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1764051033892 implements MigrationInterface {
    name = 'InitialSchema1764051033892'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "epas" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "tipoEpa" character varying NOT NULL, "descripcion" text, "sintomas" text, "manejoYControl" text, "mesesProbables" text, "temporadas" text, "notasEstacionalidad" text, "fotosSintomas" text, "fotosGenerales" text, "tags" text, "creadoPorUsuarioId" integer NOT NULL, CONSTRAINT "PK_8d23543eb1e7a3929bdf5b5805a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "epa_tipos_cultivos_wiki" ("epaId" integer NOT NULL, "tipoCultivoWikiId" integer NOT NULL, CONSTRAINT "PK_293f95ca884d33392b45f8737a3" PRIMARY KEY ("epaId", "tipoCultivoWikiId"))`);
        await queryRunner.query(`CREATE TABLE "tipos_cultivos_wiki" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "descripcion" text, CONSTRAINT "PK_b6eab974e49fd96658f753c0886" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "descripcion" character varying, "es_sistema" boolean NOT NULL DEFAULT false, "estado" character varying NOT NULL DEFAULT 'activo', CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10" UNIQUE ("nombre"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuarios_permisos" ("usuarioId" integer NOT NULL, "permisoId" integer NOT NULL, CONSTRAINT "PK_1f09d2bdf77871b31160d280a61" PRIMARY KEY ("usuarioId", "permisoId"))`);
        await queryRunner.query(`CREATE TABLE "permisos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "modulo" character varying NOT NULL, "accion" character varying NOT NULL, "clave" character varying NOT NULL, CONSTRAINT "PK_3127bd9cfeb13ae76186d0d9b38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rol_permisos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "rolId" integer NOT NULL, "permisoId" integer NOT NULL, CONSTRAINT "PK_2c68f1f399191ac33c3c248a9d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_codes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "usuarioId" integer NOT NULL, "tipo" character varying(10) NOT NULL, "code" character varying(6) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "usedAt" TIMESTAMP, CONSTRAINT "PK_6ed15013da989317f69306da6e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "apellido" character varying NOT NULL, "identificacion" character varying NOT NULL, "idFicha" character varying, "telefono" character varying, "correo" character varying NOT NULL, "passwordHash" character varying NOT NULL, "emailVerifiedAt" TIMESTAMP, "estado" character varying NOT NULL DEFAULT 'ACTIVO', "lastLoginAt" TIMESTAMP, "avatarUrl" character varying, "rolId" integer, CONSTRAINT "UQ_5731ef42819bcdc86c5a86c509c" UNIQUE ("identificacion"), CONSTRAINT "UQ_63665765c1a778a770c9bd585d3" UNIQUE ("correo"), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clientes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "identificacion" character varying NOT NULL, "telefono" character varying, "email" character varying, "direccion" character varying, "notas" text, CONSTRAINT "UQ_9bf38ce473766f59a4dcf2fbffa" UNIQUE ("identificacion"), CONSTRAINT "PK_d76bf3571d906e4e86470482c08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lotes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "geom" geometry(Polygon,4326), "areaM2" numeric(12,2), "areaHa" numeric(12,4), "centroide" geometry(Point,4326), "descripcion" character varying, "estado" character varying NOT NULL DEFAULT 'activo', CONSTRAINT "PK_6eda564423c09706b95cbf8ae1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sublotes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "lote_id" integer NOT NULL, "geom" geometry(Polygon,4326), "areaM2" numeric(12,2), "areaHa" numeric(12,4), "centroide" geometry(Point,4326), "descripcion" character varying, CONSTRAINT "PK_d456393185ac94c09d904a2bb87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cultivos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombreCultivo" character varying NOT NULL, "tipoCultivo" character varying, "descripcion" character varying, "lote_id" integer, "sublote_id" integer, "fechaSiembra" date, "fechaFinalizacion" date, "estado" character varying NOT NULL DEFAULT 'activo', "fechaCreacion" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f7b1d6fc0a6976acd023dca2d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movimientos_produccion" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "loteProduccionId" integer NOT NULL, "tipo" character varying NOT NULL, "cantidadKg" double precision NOT NULL, "costoUnitarioKg" double precision NOT NULL, "costoTotal" double precision NOT NULL, "ventaId" integer, "descripcion" text, "usuarioId" integer NOT NULL, CONSTRAINT "PK_b60c7034e7a75bb9249293644da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lotes_produccion" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "productoAgroId" integer NOT NULL, "cultivoId" integer, "loteId" integer, "subLoteId" integer, "actividadCosechaId" integer, "cantidadKg" double precision NOT NULL, "stock_disponible_kg" double precision NOT NULL, "costoUnitarioKg" double precision NOT NULL, "costoTotal" double precision NOT NULL, "precioSugeridoKg" double precision NOT NULL, CONSTRAINT "PK_245f08534328efe79cc2cc1ccd8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "productos_agro" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "unidadBase" character varying NOT NULL, "descripcion" text, CONSTRAINT "PK_3f2394dec7a57ca911917ec0c6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ventas_detalles" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "ventaId" integer NOT NULL, "productoAgroId" integer NOT NULL, "loteProduccionId" integer, "cultivoId" integer, "cantidadKg" double precision NOT NULL, "precioUnitarioKg" double precision NOT NULL, "precioTotal" double precision NOT NULL, "costoUnitarioKg" double precision NOT NULL, "costoTotal" double precision NOT NULL, CONSTRAINT "PK_9f0d45a2a28df1e30e0d4cd8b57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "pagos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "ventaId" integer NOT NULL, "metodo" character varying NOT NULL, "monto" double precision NOT NULL, "moneda" character varying NOT NULL, "referencia" character varying, CONSTRAINT "PK_37321ca70a2ed50885dc205beb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facturas" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "ventaId" integer NOT NULL, "numero" character varying NOT NULL, "prefijo" character varying NOT NULL, "fechaEmision" TIMESTAMP NOT NULL, "vencimiento" TIMESTAMP NOT NULL, "qrUrl" character varying, "pdfUrl" character varying, CONSTRAINT "REL_8416d51118716fd00fc777c7b0" UNIQUE ("ventaId"), CONSTRAINT "PK_f302947c1e4773639b20707a8bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ventas" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "fecha" TIMESTAMP NOT NULL, "clienteId" integer NOT NULL, "subtotal" double precision NOT NULL, "impuestos" double precision NOT NULL, "descuento" double precision NOT NULL, "total" double precision NOT NULL, "estado" character varying NOT NULL, "usuarioId" integer NOT NULL, "anulada_por_usuario_id" integer, "fecha_anulacion" TIMESTAMP, CONSTRAINT "PK_b8b73abe8561829c019531d9a2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipos_sensores" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "unidad" character varying NOT NULL, "decimales" integer NOT NULL DEFAULT '2', "descripcion" character varying, "imagen" character varying, "ttl_minutos" integer NOT NULL DEFAULT '5', CONSTRAINT "PK_3421868655076bc65fe3e356046" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sensor_lecturas" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "sensor_id" integer NOT NULL, "valor" double precision NOT NULL, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "unidad" character varying, "observaciones" character varying, CONSTRAINT "PK_b447a0350b6c07bb4e90c94b8d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sensores" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre_sensor" character varying NOT NULL, "tipo_sensor_id" integer NOT NULL, "protocolo" character varying NOT NULL, "endpoint_url" character varying, "mqtt_broker" character varying, "mqtt_port" integer, "mqtt_topic" character varying, "mqtt_username" character varying, "mqtt_password" character varying, "mqtt_qos" integer, "valor_minimo_sensor" double precision, "valor_maximo_sensor" double precision, "activo" boolean NOT NULL DEFAULT true, "estado_conexion" character varying NOT NULL DEFAULT 'DESCONECTADO', "ultimo_valor" double precision, "ultima_medicion" TIMESTAMP, "last_seen_at" TIMESTAMP, "cultivoId" integer, "creadoPorUsuarioId" integer, CONSTRAINT "PK_17e80466352f77aff22e06ad334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "almacenes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "descripcion" text, "ubicacion" character varying, CONSTRAINT "PK_2af9818dc2019bc97c7d26217e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categorias" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, CONSTRAINT "PK_3886a26251605c571c6b4f861fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movimientos_insumos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "insumoId" integer NOT NULL, "tipo" character varying NOT NULL, "cantidadPresentacion" double precision NOT NULL, "cantidadUso" double precision NOT NULL, "costoUnitarioPresentacion" double precision NOT NULL, "costoUnitarioUso" double precision NOT NULL, "costoTotal" double precision NOT NULL, "valorInventarioResultante" double precision NOT NULL, "descripcion" text, "actividadId" integer, "usuarioId" integer NOT NULL, "almacenOrigenId" integer, "almacenDestinoId" integer, CONSTRAINT "PK_bc8f3965426ecbfc9ab5424b4f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "insumos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "descripcion" text, "fotoUrl" character varying, "presentacionTipo" character varying NOT NULL, "presentacionCantidad" double precision NOT NULL, "presentacionUnidad" character varying NOT NULL, "unidadUso" character varying NOT NULL, "tipoMateria" character varying NOT NULL, "factorConversionUso" double precision NOT NULL, "stockPresentacion" double precision NOT NULL, "stockUso" double precision NOT NULL, "precioUnitarioPresentacion" double precision NOT NULL, "precioUnitarioUso" double precision NOT NULL, "valorInventario" double precision NOT NULL, "almacenId" integer NOT NULL, "proveedorId" integer, "categoriaId" integer NOT NULL, "fechaRegistro" TIMESTAMP NOT NULL, "creadoPorUsuarioId" integer, CONSTRAINT "PK_b4e1b727a7b140e698e3a3dc7af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proveedores" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, CONSTRAINT "PK_1dcf121f19f362fb1b4c0a493a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuario_permisos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "usuarioId" integer NOT NULL, "permisoId" integer NOT NULL, CONSTRAINT "PK_245fe30a1b490654d20cdcfb7ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_responsables" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "actividadId" integer NOT NULL, "usuarioId" integer NOT NULL, "horas" double precision NOT NULL, "precioHora" double precision NOT NULL, "costo" double precision NOT NULL, CONSTRAINT "PK_cea86013f6ee0e97666cc2bbef2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_servicios" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "actividadId" integer NOT NULL, "nombreServicio" character varying NOT NULL, "horas" double precision NOT NULL, "precioHora" double precision NOT NULL, "costo" double precision NOT NULL, CONSTRAINT "PK_2ec0c214a83cbe1ed246f5cb372" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_evidencias" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "actividadId" integer NOT NULL, "descripcion" text, "imagenes" text NOT NULL, CONSTRAINT "PK_80fe46234ea40ea9902e460ff60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_insumos_uso" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "actividadId" integer NOT NULL, "insumoId" integer NOT NULL, "cantidadUso" double precision NOT NULL, "costoUnitarioUso" double precision NOT NULL, "costoTotal" double precision NOT NULL, "movimientoInsumoId" integer, CONSTRAINT "PK_0cc0ff2c078a7616db43b05bd30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "nombre" character varying NOT NULL, "tipo" character varying NOT NULL, "subtipo" character varying NOT NULL, "loteId" integer, "subLoteId" integer, "cultivoId" integer, "fecha" TIMESTAMP NOT NULL, "horasActividad" double precision NOT NULL, "precioHoraActividad" double precision NOT NULL, "costoManoObra" double precision NOT NULL, "descripcion" text, "creado_por_usuario_id" integer NOT NULL, "creadoPorUsuarioId" integer, CONSTRAINT "PK_03490866fef1c23456f0e289d9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividad_insumos" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "actividad_id" integer NOT NULL, "insumo_id" integer NOT NULL, "cantidad_usada" double precision NOT NULL, "unidad" character varying NOT NULL, "costo_unitario" double precision NOT NULL, "costo_total" double precision NOT NULL, "actividadId" integer, "insumoId" integer, CONSTRAINT "PK_fb5408a812468877d2ddff781fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "es_sistema"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "descripcion" character varying`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "es_sistema" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "estado" character varying NOT NULL DEFAULT 'activo'`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10"`);
        await queryRunner.query(`ALTER TABLE "epa_tipos_cultivos_wiki" ADD CONSTRAINT "FK_34060e6dafef1f330d1f56c047e" FOREIGN KEY ("epaId") REFERENCES "epas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "epa_tipos_cultivos_wiki" ADD CONSTRAINT "FK_d12419b856941c0e63ed4faa12c" FOREIGN KEY ("tipoCultivoWikiId") REFERENCES "tipos_cultivos_wiki"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_permisos" ADD CONSTRAINT "FK_dc59163768441da2c17c31a2c75" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios_permisos" ADD CONSTRAINT "FK_4be7ee93f0a8b3a31ffc9116ae7" FOREIGN KEY ("permisoId") REFERENCES "permisos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permisos" ADD CONSTRAINT "FK_b39138a3ce555d2ecd72ce57540" FOREIGN KEY ("rolId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permisos" ADD CONSTRAINT "FK_a19038a8652d3e0ac882cf2141e" FOREIGN KEY ("permisoId") REFERENCES "permisos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_codes" ADD CONSTRAINT "FK_591f93ef91a40dca78c240a0254" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ADD CONSTRAINT "FK_df0c94be5a01a546bf1b9ca12ae" FOREIGN KEY ("rolId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sublotes" ADD CONSTRAINT "FK_a1545f2585322d99f726789dff8" FOREIGN KEY ("lote_id") REFERENCES "lotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos" ADD CONSTRAINT "FK_d046e8a1232094bdb97b1e412b7" FOREIGN KEY ("lote_id") REFERENCES "lotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cultivos" ADD CONSTRAINT "FK_f0e8fdd656a6e986fab1a177dc5" FOREIGN KEY ("sublote_id") REFERENCES "sublotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_produccion" ADD CONSTRAINT "FK_cac4db05776ba383d3e71b6e719" FOREIGN KEY ("loteProduccionId") REFERENCES "lotes_produccion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_produccion" ADD CONSTRAINT "FK_9bf963934b0f31e022e12a5889b" FOREIGN KEY ("ventaId") REFERENCES "ventas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_produccion" ADD CONSTRAINT "FK_c1a0b48f07c52d94c71273915bd" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes_produccion" ADD CONSTRAINT "FK_8b4ccbbdc6f39f9483de4bf1bdf" FOREIGN KEY ("productoAgroId") REFERENCES "productos_agro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lotes_produccion" ADD CONSTRAINT "FK_be81625861c486e175428f90644" FOREIGN KEY ("cultivoId") REFERENCES "cultivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" ADD CONSTRAINT "FK_921b250927ef78bdb0c1768aec8" FOREIGN KEY ("ventaId") REFERENCES "ventas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" ADD CONSTRAINT "FK_a5298acf79f34535d4cdefb123a" FOREIGN KEY ("productoAgroId") REFERENCES "productos_agro"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" ADD CONSTRAINT "FK_dc510b3c8c90b1629fb91597fad" FOREIGN KEY ("loteProduccionId") REFERENCES "lotes_produccion"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" ADD CONSTRAINT "FK_4bc5e094de3e6f53a234b4bc389" FOREIGN KEY ("cultivoId") REFERENCES "cultivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagos" ADD CONSTRAINT "FK_f2caa62513831918888a78e291c" FOREIGN KEY ("ventaId") REFERENCES "ventas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facturas" ADD CONSTRAINT "FK_8416d51118716fd00fc777c7b03" FOREIGN KEY ("ventaId") REFERENCES "ventas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_771620ab33741414f8248217fc3" FOREIGN KEY ("clienteId") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_ffe890346eb72924c06ff4df0a7" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sensor_lecturas" ADD CONSTRAINT "FK_61cebf190a7e65e30b128a12d70" FOREIGN KEY ("sensor_id") REFERENCES "sensores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sensores" ADD CONSTRAINT "FK_a66d0d9dd6a3e23a72ef0798307" FOREIGN KEY ("tipo_sensor_id") REFERENCES "tipos_sensores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sensores" ADD CONSTRAINT "FK_fe2d803bf0ab2c28b2b20839fd4" FOREIGN KEY ("cultivoId") REFERENCES "cultivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_insumos" ADD CONSTRAINT "FK_4eca2bfe7f2ee074903262cdf6b" FOREIGN KEY ("insumoId") REFERENCES "insumos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "movimientos_insumos" ADD CONSTRAINT "FK_224ddf3e66bb634845f0e3367df" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "FK_a4754101d7f9160ead1042ad2d6" FOREIGN KEY ("almacenId") REFERENCES "almacenes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "FK_8868e4cb08cfb3515bfaeef0880" FOREIGN KEY ("proveedorId") REFERENCES "proveedores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "FK_1acafbf46b10a4650b5935ee728" FOREIGN KEY ("categoriaId") REFERENCES "categorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_permisos" ADD CONSTRAINT "FK_771897508608f298a92a17c2c9a" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_permisos" ADD CONSTRAINT "FK_812a28072efb06ab4d10b328170" FOREIGN KEY ("permisoId") REFERENCES "permisos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades_responsables" ADD CONSTRAINT "FK_7f65ee769a5e15106417bd1c3eb" FOREIGN KEY ("actividadId") REFERENCES "actividades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades_responsables" ADD CONSTRAINT "FK_6729b67bc25c32db1b67eff0eaf" FOREIGN KEY ("usuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades_servicios" ADD CONSTRAINT "FK_9127a3c726625a67b864977a062" FOREIGN KEY ("actividadId") REFERENCES "actividades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades_evidencias" ADD CONSTRAINT "FK_72d6180ad340a075a07a1734193" FOREIGN KEY ("actividadId") REFERENCES "actividades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades_insumos_uso" ADD CONSTRAINT "FK_800b1e1205db8bced6d4233bbc6" FOREIGN KEY ("actividadId") REFERENCES "actividades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "FK_e6f30f9b48031252a3f532b09d8" FOREIGN KEY ("loteId") REFERENCES "lotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "FK_48edec4bb52a7253653d940117c" FOREIGN KEY ("subLoteId") REFERENCES "sublotes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "FK_07b83a195752e14b28ef3a48fdc" FOREIGN KEY ("cultivoId") REFERENCES "cultivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividades" ADD CONSTRAINT "FK_4ae1fa0d00f6046e1041cdd0191" FOREIGN KEY ("creadoPorUsuarioId") REFERENCES "usuarios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividad_insumos" ADD CONSTRAINT "FK_6ccf5bd3fb02d08bd510199947c" FOREIGN KEY ("actividadId") REFERENCES "actividades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actividad_insumos" ADD CONSTRAINT "FK_22352e2d38f759fadeab7697f30" FOREIGN KEY ("insumoId") REFERENCES "insumos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "actividad_insumos" DROP CONSTRAINT "FK_22352e2d38f759fadeab7697f30"`);
        await queryRunner.query(`ALTER TABLE "actividad_insumos" DROP CONSTRAINT "FK_6ccf5bd3fb02d08bd510199947c"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "FK_4ae1fa0d00f6046e1041cdd0191"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "FK_07b83a195752e14b28ef3a48fdc"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "FK_48edec4bb52a7253653d940117c"`);
        await queryRunner.query(`ALTER TABLE "actividades" DROP CONSTRAINT "FK_e6f30f9b48031252a3f532b09d8"`);
        await queryRunner.query(`ALTER TABLE "actividades_insumos_uso" DROP CONSTRAINT "FK_800b1e1205db8bced6d4233bbc6"`);
        await queryRunner.query(`ALTER TABLE "actividades_evidencias" DROP CONSTRAINT "FK_72d6180ad340a075a07a1734193"`);
        await queryRunner.query(`ALTER TABLE "actividades_servicios" DROP CONSTRAINT "FK_9127a3c726625a67b864977a062"`);
        await queryRunner.query(`ALTER TABLE "actividades_responsables" DROP CONSTRAINT "FK_6729b67bc25c32db1b67eff0eaf"`);
        await queryRunner.query(`ALTER TABLE "actividades_responsables" DROP CONSTRAINT "FK_7f65ee769a5e15106417bd1c3eb"`);
        await queryRunner.query(`ALTER TABLE "usuario_permisos" DROP CONSTRAINT "FK_812a28072efb06ab4d10b328170"`);
        await queryRunner.query(`ALTER TABLE "usuario_permisos" DROP CONSTRAINT "FK_771897508608f298a92a17c2c9a"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "FK_1acafbf46b10a4650b5935ee728"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "FK_8868e4cb08cfb3515bfaeef0880"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "FK_a4754101d7f9160ead1042ad2d6"`);
        await queryRunner.query(`ALTER TABLE "movimientos_insumos" DROP CONSTRAINT "FK_224ddf3e66bb634845f0e3367df"`);
        await queryRunner.query(`ALTER TABLE "movimientos_insumos" DROP CONSTRAINT "FK_4eca2bfe7f2ee074903262cdf6b"`);
        await queryRunner.query(`ALTER TABLE "sensores" DROP CONSTRAINT "FK_fe2d803bf0ab2c28b2b20839fd4"`);
        await queryRunner.query(`ALTER TABLE "sensores" DROP CONSTRAINT "FK_a66d0d9dd6a3e23a72ef0798307"`);
        await queryRunner.query(`ALTER TABLE "sensor_lecturas" DROP CONSTRAINT "FK_61cebf190a7e65e30b128a12d70"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_ffe890346eb72924c06ff4df0a7"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_771620ab33741414f8248217fc3"`);
        await queryRunner.query(`ALTER TABLE "facturas" DROP CONSTRAINT "FK_8416d51118716fd00fc777c7b03"`);
        await queryRunner.query(`ALTER TABLE "pagos" DROP CONSTRAINT "FK_f2caa62513831918888a78e291c"`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" DROP CONSTRAINT "FK_4bc5e094de3e6f53a234b4bc389"`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" DROP CONSTRAINT "FK_dc510b3c8c90b1629fb91597fad"`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" DROP CONSTRAINT "FK_a5298acf79f34535d4cdefb123a"`);
        await queryRunner.query(`ALTER TABLE "ventas_detalles" DROP CONSTRAINT "FK_921b250927ef78bdb0c1768aec8"`);
        await queryRunner.query(`ALTER TABLE "lotes_produccion" DROP CONSTRAINT "FK_be81625861c486e175428f90644"`);
        await queryRunner.query(`ALTER TABLE "lotes_produccion" DROP CONSTRAINT "FK_8b4ccbbdc6f39f9483de4bf1bdf"`);
        await queryRunner.query(`ALTER TABLE "movimientos_produccion" DROP CONSTRAINT "FK_c1a0b48f07c52d94c71273915bd"`);
        await queryRunner.query(`ALTER TABLE "movimientos_produccion" DROP CONSTRAINT "FK_9bf963934b0f31e022e12a5889b"`);
        await queryRunner.query(`ALTER TABLE "movimientos_produccion" DROP CONSTRAINT "FK_cac4db05776ba383d3e71b6e719"`);
        await queryRunner.query(`ALTER TABLE "cultivos" DROP CONSTRAINT "FK_f0e8fdd656a6e986fab1a177dc5"`);
        await queryRunner.query(`ALTER TABLE "cultivos" DROP CONSTRAINT "FK_d046e8a1232094bdb97b1e412b7"`);
        await queryRunner.query(`ALTER TABLE "sublotes" DROP CONSTRAINT "FK_a1545f2585322d99f726789dff8"`);
        await queryRunner.query(`ALTER TABLE "usuarios" DROP CONSTRAINT "FK_df0c94be5a01a546bf1b9ca12ae"`);
        await queryRunner.query(`ALTER TABLE "email_codes" DROP CONSTRAINT "FK_591f93ef91a40dca78c240a0254"`);
        await queryRunner.query(`ALTER TABLE "rol_permisos" DROP CONSTRAINT "FK_a19038a8652d3e0ac882cf2141e"`);
        await queryRunner.query(`ALTER TABLE "rol_permisos" DROP CONSTRAINT "FK_b39138a3ce555d2ecd72ce57540"`);
        await queryRunner.query(`ALTER TABLE "usuarios_permisos" DROP CONSTRAINT "FK_4be7ee93f0a8b3a31ffc9116ae7"`);
        await queryRunner.query(`ALTER TABLE "usuarios_permisos" DROP CONSTRAINT "FK_dc59163768441da2c17c31a2c75"`);
        await queryRunner.query(`ALTER TABLE "epa_tipos_cultivos_wiki" DROP CONSTRAINT "FK_d12419b856941c0e63ed4faa12c"`);
        await queryRunner.query(`ALTER TABLE "epa_tipos_cultivos_wiki" DROP CONSTRAINT "FK_34060e6dafef1f330d1f56c047e"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10" UNIQUE ("nombre")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "estado"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "es_sistema"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "descripcion"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "estado" character varying NOT NULL DEFAULT 'activo'`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "es_sistema" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "descripcion" character varying`);
        await queryRunner.query(`DROP TABLE "actividad_insumos"`);
        await queryRunner.query(`DROP TABLE "actividades"`);
        await queryRunner.query(`DROP TABLE "actividades_insumos_uso"`);
        await queryRunner.query(`DROP TABLE "actividades_evidencias"`);
        await queryRunner.query(`DROP TABLE "actividades_servicios"`);
        await queryRunner.query(`DROP TABLE "actividades_responsables"`);
        await queryRunner.query(`DROP TABLE "usuario_permisos"`);
        await queryRunner.query(`DROP TABLE "proveedores"`);
        await queryRunner.query(`DROP TABLE "insumos"`);
        await queryRunner.query(`DROP TABLE "movimientos_insumos"`);
        await queryRunner.query(`DROP TABLE "categorias"`);
        await queryRunner.query(`DROP TABLE "almacenes"`);
        await queryRunner.query(`DROP TABLE "sensores"`);
        await queryRunner.query(`DROP TABLE "sensor_lecturas"`);
        await queryRunner.query(`DROP TABLE "tipos_sensores"`);
        await queryRunner.query(`DROP TABLE "ventas"`);
        await queryRunner.query(`DROP TABLE "facturas"`);
        await queryRunner.query(`DROP TABLE "pagos"`);
        await queryRunner.query(`DROP TABLE "ventas_detalles"`);
        await queryRunner.query(`DROP TABLE "productos_agro"`);
        await queryRunner.query(`DROP TABLE "lotes_produccion"`);
        await queryRunner.query(`DROP TABLE "movimientos_produccion"`);
        await queryRunner.query(`DROP TABLE "cultivos"`);
        await queryRunner.query(`DROP TABLE "sublotes"`);
        await queryRunner.query(`DROP TABLE "lotes"`);
        await queryRunner.query(`DROP TABLE "clientes"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "email_codes"`);
        await queryRunner.query(`DROP TABLE "rol_permisos"`);
        await queryRunner.query(`DROP TABLE "permisos"`);
        await queryRunner.query(`DROP TABLE "usuarios_permisos"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "tipos_cultivos_wiki"`);
        await queryRunner.query(`DROP TABLE "epa_tipos_cultivos_wiki"`);
        await queryRunner.query(`DROP TABLE "epas"`);
    }

}
